### ISSUE TITLE
Local Caching

### ISSUE THREAD

**Issue by YoungMaker** [YoungMaker/iORC#15]
Figure out how to implement an app-local cache or database so that not all requests for information will have to go to the API

**Comment by YoungMaker** [comment]
Apollo should be set up for at least [HTTP level caching](https://github.com/apollographql/apollo-android) for Milestone 2

**Comment by YoungMaker** [comment]
@hwilling has agreed to attempt this before ms2. If its more complicated that a few settings or packages then MS3 is the new goal

**Comment by hwilling** [comment]
changing this to milestone 3 due to the apollo documentation and not wanting to destabilize the current build

**Comment by hwilling** [comment]
This might be a bit more involved than I thought, it'll be done for next milestone but I'm not 100% sure how long it'll take. Most likely more than this weekend unless I make a breakthrough tomorrow/Sunday

**Comment by hwilling** [comment]
method for caching has been implemented and is being used for characters, race and classes as of commit ea52b42. this can be applied to future list types
