### ISSUE TITLE
Untangle branches for UI development

### ISSUE THREAD

**Issue by YoungMaker** [YoungMaker/iORC#21]
The ```diceWidget``` branch and the ```basicFlow``` branch have differences. Please pick one branch to develop on, and continue the dice widget work there until completed. In the future, do not merge directly. Instead, create and open a pull request to merge the two, and have all the other members sign off on it before merging.

**Comment by YoungMaker** [comment]
I had a look at the network page for the repo and it looks like the ```baicFlow``` branch has all of the ```diceWidget``` contents in it, plus one more work commit? @l-hurd314, please confirm and then close the ```diceWidget``` branch if development there has ended.

**Comment by l-hurd314** [comment]
Development in the diceWidget branch is not complete yet. You can back track the BasicFlow branch to before I merged. Once I finish the diceWidget branch I will create a pull request.

**Comment by YoungMaker** [comment]
We sorted the ```basicFlow``` branch (by deleting it) but not the ```diceWidget``` branch. That will have to be merged manually.

**Comment by YoungMaker** [comment]
The ```diceWidget``` branch was merged into the feature branch ```detailPanes``` successfully in #26
