### ISSUE TITLE
The layout of the Character page does not reorder

### ISSUE THREAD

**Issue by YoungMaker** [YoungMaker/iORC#28]
The character page layout does not re-align to fit landscape or high dpi screens. It should not be locked into the current grid.

**Comment by hwilling** [comment]
Maybe reconfigure which containers are used to allow for a more flexible transition? I'll look into it a bit more soon

**Comment by l-hurd314** [comment]
The character page layout now re-aligns to the screen to fit landscape.

**Comment by YoungMaker** [comment]
@l-hurd314 is this issue closed then? or is more work necessary. Please update these issues when you fix them with detailed accounts

**Comment by l-hurd314** [comment]
The character sheet stays ordered even when changed to landscape. And the variables in the character sheet are dynamic.
