### ISSUE TITLE
Add Grid Layout in diceWidget

### ISSUE THREAD

**Issue by l-hurd314** [YoungMaker/iORC#29]
Use a grid layout for the diceWidget image buttons in order to keep them organized. As of now they are independently placed in the layout therefore they will not stay organized when the layout is changed to landscape.

**Comment by YoungMaker** [comment]
Suggest you look into things other than grid layout. The layout should be dynamic and fill any size screen but should not clip into each other.

**Comment by l-hurd314** [comment]
The diceWidget now has a grid layout implemented for the buttons. The buttons do not collide anymore but they are still not completely organized on the screen.
