### ISSUE TITLE
Characters can be created and saved to the cloud. 

### ISSUE THREAD

**Issue by YoungMaker** [YoungMaker/iORC#31]
With use of the API, characters can be saved to the cloud and recalled, edited and deleted.

**Comment by YoungMaker** [comment]
- Users characters are saved on the cloud server and are associated with their account. 
- When users log in their previously saved characters appear
- Users can edit their previously saved characters or delete them.

**Comment by YoungMaker** [comment]
For MS2 we're removing uses from the user story. Characters will be created and stored without users,

**Comment by hwilling** [comment]
characters can be saved and called to the character list. now down to edit and delete.
