### ISSUE TITLE
M/D switching does not retain state after back

### ISSUE THREAD

**Issue by YoungMaker** [YoungMaker/iORC#34]
Pressing back in the Classes/Races detail and the Alignment/Religion detail panes does not respect the state of the activity and it reverts to classes or alignments. This should be fixed for tomorrow if possible. Thanks

**Comment by hwilling** [comment]
Okay thank you I overlooked testing that. looks like it will be a quick fix, I'll get to it in an hour or so

**Comment by hwilling** [comment]
this issue should be taken care of with commit 6a1605c, closing issue.
