### ISSUE TITLE
App crashes when pressing back out of class detail page 

### ISSUE THREAD

**Issue by YoungMaker** [YoungMaker/iORC#48]
Probably due to not properly processing the intent extras? Idk.

**Comment by YoungMaker** [comment]
This is kind of a duplicate of #47 except I wouldn't know that by looking at it. Pls fix

**Comment by hwilling** [comment]
@YoungMaker you were correct earlier this is a different issue to #47. The fix to this was in 
85f4e3e where the null checker was put back in
