### ISSUE TITLE
Add Apollo for android dependency

### ISSUE THREAD

**Issue by YoungMaker** [YoungMaker/iORC#5]

**Comment by YoungMaker** [comment]
This will be difficult for Milestone one as we will probably be adding Apollo which will handle data binding for graphQL

**Comment by YoungMaker** [comment]
Changed this to reference the new Apollo package we're going to be using to accomplish this

**Comment by hwilling** [comment]
I'm assuming this is what we are looking for?
https://github.com/apollographql/apollo-android

**Comment by hwilling** [comment]
apollo plugin appears to be in. We'll need to insert the schema and a graphql query file in order to connect the app and the api

**Comment by YoungMaker** [comment]
Since this package has been well and truly integrated with dev work cited above, I'm confident we can close this issue. Please weigh in @hwilling before closing if you see fit.

**Comment by hwilling** [comment]
Yeah I think this issue can be closed. The dependency is added and I should make a separate issue for any work that remains related to this
