### ISSUE TITLE
Implement Alignments and Religions

### ISSUE THREAD

**Issue by YoungMaker** [YoungMaker/iORC#62]
The alignment and religions are added as VersionInfo text objects on the server. Shortly I will include a list of Queries and mutations related to getting them. 

There is currently no way to attach them to a character, but I'm working on that. It will either be as part of the modifier system or (more likely) be added as a new parameter to the character objects.

Item class, currency name, and any other text only properties can be added to the version info with this system. These new features need to be added to the app core.

**Comment by hwilling** [comment]
The alignment and religions are pulled from the db and added to the data used to create the character as of commit aaefd5c
