### ISSUE TITLE
Character page does not refresh when creating a new character

### ISSUE THREAD

**Issue by YoungMaker** [YoungMaker/iORC#70]
The snackbar popup comes up but the character list did not refresh. Tested under the latest build in the `skillsList` branch

**Comment by hwilling** [comment]
character list refreshed both times that I tested this

**Comment by hwilling** [comment]
issue was most likely caused by snackbar being created on button press to finish creating character instead of being called when the creation mutation returns successful

**Comment by YoungMaker** [comment]
This issue is occurring on my phone using 4g. Might just be long connection times. This is not on the caching branch it is on a `skillsList` build.

**Comment by hwilling** [comment]
yeah i tested it on skillsList it's most likely due to a delayed connection combined with when the snackbar has been created, I moved the location of the snackbar creation and am committing it now

**Comment by hwilling** [comment]
okay I will then

**Comment by hwilling** [comment]
Yes there was a little bit of a delay

**Comment by hwilling** [comment]
It seems fine with this updated creation location though, the only thing that could cause a delay with the list refresh is if the query that gets the refreshed list takes time to return or does not return, however, it will only say that the character has been created if the character creation mutation returns as a succcess

**Comment by hwilling** [comment]
@YoungMaker is this good to close then?

**Comment by YoungMaker** [comment]
Confirmed. Closed in 0d3872e
