### ISSUE TITLE
Loading spinner does not go away after characters are loaded from the API.

### ISSUE THREAD

**Issue by YoungMaker** [YoungMaker/iORC#81]
Might have to do with the fact that caching does not make a response?

**Comment by l-hurd314** [comment]
I know what the problem is and I can fix it. But should I wait until Hunter fixes issue #80?

**Comment by l-hurd314** [comment]
I have fixed the issue as of commit 1ac7b606 on the LoadingPanel branch. Should I issue an pull request?
