### ISSUE TITLE
There are two fabs in the Inventory panel

### ISSUE THREAD

**Issue by YoungMaker** [YoungMaker/iORC#89]
One fab per activity as per the design ethos at google. Two is downright confusing. You can stack actions in the fab though if you really wanted to. Instead, I will make this into a menu item w/ icon

**Comment by l-hurd314** [comment]
Okay, my bad.

**Comment by YoungMaker** [comment]
@l-hurd314 I will resolve this issue when I begin work on that panel later today.

**Comment by hwilling** [comment]
addressed issue in commit 022d74d
